<?php

namespace Netauratech\CoreCms\Http\Controllers;

use Illuminate\Http\JsonResponse;
use Netauratech\CoreCms\Contracts\ChallengeGeneratorInterface;
use Illuminate\Http\Response;
use Netauratech\CoreCms\Contracts\ChallengeInterface;
use Netauratech\CoreCms\Http\Requests\CaptchaRequest;

class CaptchaController extends Controller
{
    protected ChallengeGeneratorInterface $challengeGenerator;
    protected ChallengeInterface $challenge;

    public function __construct(ChallengeGeneratorInterface $challengeGenerator, ChallengeInterface $challenge)
    {
        $this->challengeGenerator = $challengeGenerator;
        $this->challenge = $challenge;
    }

    /**
     * Serves the captcha puzzle image for a given key.
     *
     * @param string $key The challenge key generated by PuzzleChallenge.
     * @return Response The captcha image.
     */
    public function show(string $key): Response
    {
        return $this->challengeGenerator->generate($key);
    }

    /**
     * Handles verification of the captcha solution submitted by the user.
     *
     * This method validates the captcha request and uses the implementation
     * of ChallengeInterface to verify whether the response provided matches
     * the expected solution to the challenge.
     *
     * @param CaptchaRequest $request The HTTP request containing the captcha data (challenge and answer).
     * @param ChallengeInterface $challenge The instance of the challenge management service (e.g., PuzzleChallenge).
     * @return Response An HTTP 204 (No Content) response if the verification is successful,
     * or an HTTP 422 (Unprocessable Entity) response if the captcha verification fails.
     */
    public function check(CaptchaRequest $request, ChallengeInterface $challenge): Response
    {
        $data = $request->validated();
        if($challenge->check($data['challenge'], $data['answer'])) {
            return new Response(null, 204);
        }
        return new Response(null, 422);
    }

    public function generate(): JsonResponse
    {
        return new JsonResponse(['key' => $this->challenge->generateKey()], 200);
    }
}